/**
 * Technique 28: Stream error handling
 * 	- the stream classes inherit from EventEmitter, which means sane error
 * 		handling comes as standard.
 *
 * Problem:
 * 	- you want to catch errors generated by a stream
 * Solution:
 * 	- add an 'error' listener
 *
 * 	- the standard behavior of EventEmitter is to throw an exception when an
 * 		error event is emitted, unless there's a listener attached to the error
 * 		event. The first argument to the listener will be the error that was
 * 		raised, a decendent of the erorr object
 */
var fs = require('fs');
// cause an error to be generated by trying to open a file that doesn't exist
var stream = fs.createReadStream('not-found');
// use the events API to attach an error handler
stream.on('error', function(err) {
  console.trace();
  console.error('Stack:', err.stack);
  console.error('The error raised was:', err);
});
